(function(){"use strict";const STORAGE_KEY="depo-stok-records-v1";const MOVEMENT_KEY="depo-stok-movements-v1";const LOCATIONS=["A-1-1","A-1-2","A-1-3","A-2-1","A-2-2","A-2-3","B-1-1","B-1-2","B-1-3","B-2-1","B-2-2","B-2-3","C-1-1","C-1-2","C-1-3","C-2-1","C-2-2","C-2-3","D-1-1","D-1-2","D-1-3","D-2-1","D-2-2","D-2-3"];
const els={tabs:Array.from(document.querySelectorAll(".tab")),views:Array.from(document.querySelectorAll(".view")),searchInput:document.getElementById("searchInput"),clearSearchButton:document.getElementById("clearSearchButton"),filterLocation:document.getElementById("filterLocation"),filterStock:document.getElementById("filterStock"),filterColor:document.getElementById("filterColor"),filterSize:document.getElementById("filterSize"),clearFiltersButton:document.getElementById("clearFiltersButton"),resultList:document.getElementById("resultList"),locationGrid:document.getElementById("locationGrid"),form:document.getElementById("stockForm"),recordId:document.getElementById("recordId"),location:document.getElementById("location"),name:document.getElementById("name"),code:document.getElementById("code"),color:document.getElementById("color"),size:document.getElementById("size"),quantity:document.getElementById("quantity"),note:document.getElementById("note"),resetFormButton:document.getElementById("resetFormButton"),movementForm:document.getElementById("movementForm"),movementRecord:document.getElementById("movementRecord"),movementQuantity:document.getElementById("movementQuantity"),movementNote:document.getElementById("movementNote"),movementList:document.getElementById("movementList"),movementTypeButtons:Array.from(document.querySelectorAll("[data-movement-type]")),countList:document.getElementById("countList"),resetCountButton:document.getElementById("resetCountButton"),applyCountButton:document.getElementById("applyCountButton"),productCount:document.getElementById("productCount"),stockCount:document.getElementById("stockCount"),locationCount:document.getElementById("locationCount"),backupButton:document.getElementById("backupButton"),exportButton:document.getElementById("exportButton"),importButton:document.getElementById("importButton"),importFile:document.getElementById("importFile"),deleteAllButton:document.getElementById("deleteAllButton"),emptyTemplate:document.getElementById("emptyTemplate")};
let records=loadArray(STORAGE_KEY);let movements=loadArray(MOVEMENT_KEY);let movementType="in";
function loadArray(key){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):[]}catch(error){alert("Kayitlar okunamadi. Yedegin varsa geri yukleyebilirsin.");return[]}}
function saveAll(){localStorage.setItem(STORAGE_KEY,JSON.stringify(records));localStorage.setItem(MOVEMENT_KEY,JSON.stringify(movements))}
function uid(){return crypto&&crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())}
function normalize(value){return String(value||"").trim().toLocaleLowerCase("tr-TR")}
function switchView(viewId){els.tabs.forEach(tab=>tab.classList.toggle("active",tab.dataset.view===viewId));els.views.forEach(view=>view.classList.toggle("active",view.id===viewId));if(viewId==="countView")renderCount()}
function locationOptions(includeAll){const first=includeAll?'<option value="all">Tum lokasyonlar</option>':"";return first+LOCATIONS.map(location=>'<option value="'+location+'">'+location+'</option>').join("")}
function fillLocations(){els.location.innerHTML=locationOptions(false);els.filterLocation.innerHTML=locationOptions(true);els.locationCount.textContent=String(LOCATIONS.length)}
function emptyNode(message){const node=els.emptyTemplate.content.firstElementChild.cloneNode(true);node.querySelector("span").textContent=message;return node}
function productKey(record){return normalize(record.code)+"|"+normalize(record.name)+"|"+normalize(record.color)+"|"+normalize(record.size)}
function recordLabel(record){return record.name+" / "+record.code+" / "+record.location+" / "+(record.color||"-")+" / "+(record.size||"-")+" / "+record.quantity+" adet"}
function filteredRecords(){const term=normalize(els.searchInput.value);const location=els.filterLocation.value;const stock=els.filterStock.value;const color=normalize(els.filterColor.value);const size=normalize(els.filterSize.value);return records.filter(record=>{const qty=Number(record.quantity)||0;if(term&&!normalize(record.name).includes(term)&&!normalize(record.code).includes(term))return false;if(location&&location!=="all"&&record.location!==location)return false;if(stock==="positive"&&qty<=0)return false;if(stock==="zero"&&qty!==0)return false;if(color&&!normalize(record.color).includes(color))return false;if(size&&!normalize(record.size).includes(size))return false;return true})}
function groupedProducts(sourceRecords){const map=new Map;sourceRecords.forEach(record=>{const key=productKey(record);if(!map.has(key)){map.set(key,{name:record.name,code:record.code,color:record.color,size:record.size,note:record.note,total:0,rows:[]})}const item=map.get(key);item.total+=Number(record.quantity)||0;item.rows.push(record)});return Array.from(map.values()).sort((a,b)=>a.name.localeCompare(b.name,"tr"))}
function renderSummary(){els.productCount.textContent=String(new Set(records.map(productKey)).size);els.stockCount.textContent=String(records.reduce((sum,record)=>sum+(Number(record.quantity)||0),0))}
function renderResults(){const products=groupedProducts(filteredRecords());els.resultList.innerHTML="";if(!products.length){els.resultList.appendChild(emptyNode("Aramana veya filtrelere uygun urun bulunamadi."));return}products.forEach(product=>{const card=document.createElement("article");card.className="product-card";const locations=product.rows.map(row=>escapeHtml(row.location)+": "+escapeHtml(row.quantity)+" adet").join("<br>");card.innerHTML='<div class="card-head"><div class="card-title"><strong>'+escapeHtml(product.name)+'</strong><span>'+escapeHtml(product.code)+'</span></div><span class="badge">'+product.total+' adet</span></div><div class="meta-grid"><div class="meta"><span>Renk</span><strong>'+escapeHtml(product.color||"-")+'</strong></div><div class="meta"><span>Beden</span><strong>'+escapeHtml(product.size||"-")+'</strong></div><div class="meta"><span>Lokasyon</span><strong>'+locations+'</strong></div><div class="meta"><span>Kayit</span><strong>'+product.rows.length+' lokasyon</strong></div></div>'+(product.note?'<p class="note">'+escapeHtml(product.note)+'</p>':"");els.resultList.appendChild(card)})}
function renderMovementOptions(){els.movementRecord.innerHTML=records.length?records.map(record=>'<option value="'+record.id+'">'+escapeHtml(recordLabel(record))+'</option>').join(""):'<option value="">Once urun ekle</option>'}
function renderMovements(){els.movementList.innerHTML="";if(!movements.length){els.movementList.appendChild(emptyNode("Henuz stok hareketi yok."));return}movements.slice(0,30).forEach(move=>{const card=document.createElement("article");card.className="movement-card";const badgeClass=move.type==="out"?"badge out":move.type==="count"?"badge diff":"badge";card.innerHTML='<div class="card-head"><div class="card-title"><strong>'+escapeHtml(move.name)+'</strong><span>'+escapeHtml(move.code)+' / '+escapeHtml(move.location)+'</span></div><span class="'+badgeClass+'">'+movementName(move.type)+' '+signedQty(move)+'</span></div><p class="note">'+formatDate(move.createdAt)+(move.note?' - '+escapeHtml(move.note):'')+'</p>';els.movementList.appendChild(card)})}
function movementName(type){if(type==="in")return"Giris";if(type==="out")return"Cikis";return"Sayim"}
function signedQty(move){const qty=Number(move.quantity)||0;if(move.type==="out")return"-"+qty;if(move.type==="count"&&qty>0)return"+"+qty;return String(qty)}
function formatDate(value){try{return new Date(value).toLocaleString("tr-TR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"})}catch(error){return""}}
function renderLocations(){els.locationGrid.innerHTML="";LOCATIONS.forEach(location=>{const locationRecords=records.filter(record=>record.location===location).sort((a,b)=>a.name.localeCompare(b.name,"tr"));const total=locationRecords.reduce((sum,record)=>sum+(Number(record.quantity)||0),0);const details=document.createElement("details");details.className="location-card";if(locationRecords.length)details.open=true;const body=locationRecords.length?locationRecords.map(record=>'<div class="location-row"><strong>'+escapeHtml(record.name)+'</strong> ('+escapeHtml(record.code)+')<br>'+escapeHtml(record.color||"-")+' / '+escapeHtml(record.size||"-")+' - '+record.quantity+' adet<div class="card-actions"><button class="small-button" type="button" data-move="'+record.id+'">Giris/Cikis</button><button class="small-button" type="button" data-edit="'+record.id+'">Duzenle</button><button class="small-button danger" type="button" data-delete="'+record.id+'">Sil</button></div></div>').join(""):'<div class="location-row">Bu lokasyonda urun yok.</div>';details.innerHTML='<summary><strong>'+location+'</strong><span>'+locationRecords.length+' kayit - '+total+' adet</span></summary><div class="location-body">'+body+'</div>';els.locationGrid.appendChild(details)})}
function renderCount(){els.countList.innerHTML="";if(!records.length){els.countList.appendChild(emptyNode("Sayim icin once urun ekle."));return}records.slice().sort((a,b)=>a.location.localeCompare(b.location,"tr")||a.name.localeCompare(b.name,"tr")).forEach(record=>{const card=document.createElement("article");card.className="count-card";card.innerHTML='<div class="card-head"><div class="card-title"><strong>'+escapeHtml(record.name)+'</strong><span>'+escapeHtml(record.code)+' / '+escapeHtml(record.location)+' / '+escapeHtml(record.color||"-")+' / '+escapeHtml(record.size||"-")+'</span></div><span class="badge">Mevcut '+record.quantity+'</span></div><input type="number" min="0" step="1" inputmode="numeric" data-count="'+record.id+'" value="'+record.quantity+'" aria-label="Sayilan miktar"><div class="count-diff" data-diff="'+record.id+'">Fark: 0</div>';els.countList.appendChild(card)})}
function renderAll(){renderSummary();renderResults();renderMovementOptions();renderMovements();renderLocations();renderCount()}
function resetForm(){els.recordId.value="";els.form.reset();els.location.value=LOCATIONS[0]}
function fillForm(record){els.recordId.value=record.id;els.location.value=record.location;els.name.value=record.name;els.code.value=record.code;els.color.value=record.color;els.size.value=record.size;els.quantity.value=record.quantity;els.note.value=record.note;switchView("formView");window.scrollTo({top:0,behavior:"smooth"})}
function addMovement(record,type,quantity,note){movements.unshift({id:uid(),recordId:record.id,type,quantity,name:record.name,code:record.code,location:record.location,color:record.color,size:record.size,note:note||"",createdAt:new Date().toISOString()})}
function handleSubmit(event){event.preventDefault();const nextRecord={id:els.recordId.value||uid(),location:els.location.value,name:els.name.value.trim(),code:els.code.value.trim(),color:els.color.value.trim(),size:els.size.value.trim(),quantity:Number(els.quantity.value),note:els.note.value.trim(),updatedAt:new Date().toISOString()};if(!nextRecord.name||!nextRecord.code||Number.isNaN(nextRecord.quantity)){alert("Urun ismi, urun kodu ve stok miktari gerekli.");return}const existingIndex=records.findIndex(record=>record.id===nextRecord.id);if(existingIndex>=0){records[existingIndex]=nextRecord}else{records.unshift(nextRecord);addMovement(nextRecord,"in",nextRecord.quantity,"Ilk stok kaydi")}saveAll();resetForm();renderAll();switchView("searchView")}
function handleMovement(event){event.preventDefault();const record=records.find(item=>item.id===els.movementRecord.value);const qty=Number(els.movementQuantity.value);if(!record){alert("Once urun secmelisin.");return}if(!qty||qty<1){alert("Miktar 1 veya daha fazla olmali.");return}if(movementType==="out"&&qty>Number(record.quantity)){alert("Cikis miktari mevcut stoktan fazla olamaz.");return}record.quantity=movementType==="in"?Number(record.quantity)+qty:Number(record.quantity)-qty;record.updatedAt=new Date().toISOString();addMovement(record,movementType,qty,els.movementNote.value.trim());els.movementForm.reset();saveAll();renderAll();switchView("movementView")}
function updateCountDiff(input){const record=records.find(item=>item.id===input.dataset.count);const diffEl=document.querySelector('[data-diff="'+input.dataset.count+'"]');if(!record||!diffEl)return;const counted=Number(input.value);const diff=(Number.isNaN(counted)?0:counted)-Number(record.quantity);diffEl.textContent="Fark: "+(diff>0?"+":"")+diff;diffEl.style.color=diff===0?"var(--muted)":diff<0?"var(--danger)":"var(--accent-strong)"}
function applyCount(){const inputs=Array.from(document.querySelectorAll("[data-count]"));let changed=0;inputs.forEach(input=>{const record=records.find(item=>item.id===input.dataset.count);if(!record)return;const counted=Number(input.value);if(Number.isNaN(counted)||counted<0)return;const oldQty=Number(record.quantity)||0;const diff=counted-oldQty;if(diff!==0){record.quantity=counted;record.updatedAt=new Date().toISOString();addMovement(record,"count",diff,"Genel sayim: eski "+oldQty+", yeni "+counted);changed++}});if(!changed){alert("Uygulanacak fark yok.");return}saveAll();renderAll();alert(changed+" kayit sayima gore guncellendi.")}
function clearFilters(){els.filterLocation.value="all";els.filterStock.value="all";els.filterColor.value="";els.filterSize.value="";renderResults()}
function csvCell(value){return '"'+String(value==null?"":value).replace(/"/g,'""')+'"'}
function exportCsv(){const rows=[["Lokasyon","Urun Ismi","Urun Kodu","Renk","Beden","Stok Miktari","Aciklama","Guncelleme"]];records.forEach(record=>rows.push([record.location,record.name,record.code,record.color,record.size,record.quantity,record.note,record.updatedAt]));rows.push([],["Hareket Tipi","Tarih","Lokasyon","Urun Ismi","Urun Kodu","Renk","Beden","Miktar","Not"]);movements.forEach(move=>rows.push([movementName(move.type),formatDate(move.createdAt),move.location,move.name,move.code,move.color,move.size,signedQty(move),move.note]));const csv="﻿"+rows.map(row=>row.map(csvCell).join(";")).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="depo-stok-excel-"+new Date().toISOString().slice(0,10)+".csv";document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
function escapeHtml(value){return String(value||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function downloadBackup(){const payload={app:"depo-stok",version:2,exportedAt:new Date().toISOString(),records,movements};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="depo-stok-yedek-"+new Date().toISOString().slice(0,10)+".json";document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
function importBackup(file){const reader=new FileReader;reader.onload=()=>{try{const payload=JSON.parse(String(reader.result||"{}"));records=(Array.isArray(payload.records)?payload.records:[]).filter(record=>LOCATIONS.includes(record.location)).map(record=>({id:record.id||uid(),location:record.location,name:String(record.name||"").trim(),code:String(record.code||"").trim(),color:String(record.color||"").trim(),size:String(record.size||"").trim(),quantity:Number(record.quantity)||0,note:String(record.note||"").trim(),updatedAt:record.updatedAt||new Date().toISOString()})).filter(record=>record.name&&record.code);movements=Array.isArray(payload.movements)?payload.movements:[];saveAll();renderAll();alert("Yedek geri yuklendi.")}catch(error){alert("Bu yedek dosyasi okunamadi.")}};reader.readAsText(file)}
function bindEvents(){els.tabs.forEach(tab=>tab.addEventListener("click",()=>switchView(tab.dataset.view)));els.searchInput.addEventListener("input",renderResults);els.clearSearchButton.addEventListener("click",()=>{els.searchInput.value="";renderResults();els.searchInput.focus()});[els.filterLocation,els.filterStock,els.filterColor,els.filterSize].forEach(el=>el.addEventListener("input",renderResults));els.clearFiltersButton.addEventListener("click",clearFilters);els.form.addEventListener("submit",handleSubmit);els.resetFormButton.addEventListener("click",resetForm);els.movementForm.addEventListener("submit",handleMovement);els.movementTypeButtons.forEach(button=>button.addEventListener("click",()=>{movementType=button.dataset.movementType;els.movementTypeButtons.forEach(item=>item.classList.toggle("active",item===button))}));els.backupButton.addEventListener("click",downloadBackup);els.exportButton.addEventListener("click",exportCsv);els.importButton.addEventListener("click",()=>els.importFile.click());els.importFile.addEventListener("change",()=>{const file=els.importFile.files&&els.importFile.files[0];if(file)importBackup(file);els.importFile.value=""});els.deleteAllButton.addEventListener("click",()=>{const confirmed=confirm("Tum stok ve hareket kayitlari silinsin mi? Bu islem geri alinamaz.");if(!confirmed)return;records=[];movements=[];saveAll();resetForm();renderAll()});els.locationGrid.addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;const editId=button.dataset.edit;const deleteId=button.dataset.delete;const moveId=button.dataset.move;if(editId){const record=records.find(item=>item.id===editId);if(record)fillForm(record)}if(moveId){els.movementRecord.value=moveId;switchView("movementView");window.scrollTo({top:0,behavior:"smooth"})}if(deleteId){const confirmed=confirm("Bu kayit silinsin mi?");if(!confirmed)return;records=records.filter(record=>record.id!==deleteId);saveAll();renderAll()}});els.countList.addEventListener("input",event=>{if(event.target.matches("[data-count]"))updateCountDiff(event.target)});els.resetCountButton.addEventListener("click",renderCount);els.applyCountButton.addEventListener("click",applyCount)}
if("serviceWorker"in navigator){window.addEventListener("load",()=>{navigator.serviceWorker.register("sw.js").catch(()=>{})})}fillLocations();bindEvents();renderAll()})();
